### ISSUE TITLE
Unable to build micropython esp8266 port with this project

### ISSUE THREAD

**Issue by larsks** [esp-open-sdk/esp-open-sdk#11]
I was hoping to use this project to build the [micropython](https://micropython.org) esp8266 port, since it's the older pfalcon/esp-open-sdk is no longer maintained. Everything seems to go fine until the linking step, which fails with:

```
LINK build-GENERIC/firmware.elf
/home/sdk/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libmain.a(app_main.o): In function `system_phy_freq_trace_enable':
(.irom0.text+0x6e4): undefined reference to `user_pre_init'
/home/sdk/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libmain.a(app_main.o): In function `flash_data_check':
(.irom0.text+0x780): undefined reference to `user_pre_init'
make: Leaving directory '/build/ports/esp8266'
make: *** [Makefile:223: build-GENERIC/firmware.elf] Error 1
```

Nothing in the micropython source tree provides `user_pre_init`; is this supposed to come from somewhere in the extensa toolset, or does micropython expect an older version of the tools?

I'm building like this:

```
$ cd micropython
$ podman run --rm --userns keep-id -v $PWD/build -w /build ghcr.io/esp-open-sdk/esp-open-sdk/esp-open-sdk:latest make -C ports/esp8266/
```

**Comment by larsks** [comment]
Oh, I bet [this](https://piers.rocks/esp8266/espressif/sdk/2018/11/02/esp8266-sdk-v3.0-user_pre_init.html) is my answer.

**Comment by igagis** [comment]
Right, SDK version 3.x.x require `user_pre_init`. Aee also another issue #10 exactly about building the MicroPython.

**Comment by igagis** [comment]
Closing the issue as it is not related to this SDK, but to micropython.
